-- Seed events for Cultured London
-- Run this in Supabase SQL Editor

INSERT INTO events (title, description, start_datetime, end_datetime, venue_name, venue_address, area, categories, tags, people, is_free, price_min, price_max, event_url, source, source_id)
VALUES
  ('Brian Eno: Ambient Music in the Age of AI', 'A rare evening conversation with Brian Eno exploring generative music, artificial intelligence, and the future of creativity. Moderated by Will Self.', '2026-05-09T19:30:00', '2026-05-09T21:30:00', 'Barbican Centre', 'Silk St, London EC2Y 8DS', 'City', ARRAY['music','talk'], ARRAY['ambient','AI','generative music','electronic'], ARRAY['Brian Eno','Will Self'], false, 18.0, 30.0, 'https://www.barbican.org.uk', 'seed', 'seed-001'),
  ('Floating Points: Live at Fabric', 'Sam Shepherd (Floating Points) plays a rare live electronic set in Room 1 at Fabric. Expect his signature fusion of jazz, house, and electronic exploration.', '2026-05-07T22:00:00', '2026-05-08T05:00:00', 'Fabric', '77a Charterhouse St, London EC1M 6HJ', 'Farringdon', ARRAY['music'], ARRAY['electronic','jazz','house','club night'], ARRAY['Floating Points'], false, 20.0, 25.0, 'https://www.fabriclondon.com', 'seed', 'seed-002'),
  ('London Symphony Orchestra: Mahler Symphony No. 9', 'Sir Simon Rattle conducts the LSO in a landmark performance of Mahler''s final completed symphony.', '2026-05-12T19:30:00', NULL, 'Barbican Centre', 'Silk St, London EC2Y 8DS', 'City', ARRAY['music'], ARRAY['classical','orchestral','Mahler'], ARRAY['Simon Rattle','London Symphony Orchestra'], false, 22.0, 65.0, 'https://www.barbican.org.uk', 'seed', 'seed-003'),
  ('Caroline Polachek: New Album Tour', 'Caroline Polachek brings her acclaimed avant-pop to Brixton Academy.', '2026-05-16T19:00:00', NULL, 'O2 Academy Brixton', '211 Stockwell Rd, London SW9 9SL', 'Brixton', ARRAY['music'], ARRAY['pop','avant-pop','indie','live music'], ARRAY['Caroline Polachek'], false, 30.0, 40.0, 'https://www.academymusicgroup.com', 'seed', 'seed-004'),
  ('Free Jazz Afternoon: New Directions in Improvisation', 'An afternoon of experimental jazz featuring three emerging London-based ensembles.', '2026-05-06T15:00:00', '2026-05-06T18:00:00', 'Café OTO', '18-22 Ashwin St, London E8 3DL', 'Dalston', ARRAY['music'], ARRAY['jazz','free jazz','improvisation','experimental'], '{}', true, NULL, NULL, 'https://www.cafeoto.co.uk', 'seed', 'seed-005'),
  ('Digital Wilderness — AI-Generated Ecologies', 'A major exhibition at Serpentine exploring how artists use machine learning to imagine alternative ecosystems.', '2026-05-05T10:00:00', '2026-08-02T18:00:00', 'Serpentine Gallery', 'Kensington Gardens, London W2 3XA', 'Kensington', ARRAY['art','exhibition'], ARRAY['AI art','generative','ecology','digital'], ARRAY['Refik Anadol','Holly Herndon'], true, NULL, NULL, 'https://www.serpentinegalleries.org', 'seed', 'seed-006'),
  ('Zanele Muholi: Eye Me', 'A major retrospective of South African visual activist Zanele Muholi at Tate Modern — 260 works.', '2026-05-05T10:00:00', '2026-07-03T18:00:00', 'Tate Modern', 'Bankside, London SE1 9TG', 'South Bank', ARRAY['art','exhibition'], ARRAY['photography','portraiture','activism','queer'], ARRAY['Zanele Muholi'], false, 18.0, NULL, 'https://www.tate.org.uk', 'seed', 'seed-007'),
  ('Hackney Wick Open Studios Weekend', 'Over 200 artists open their studios across Hackney Wick and Fish Island. Free to attend.', '2026-05-10T11:00:00', '2026-05-11T18:00:00', 'Hackney Wick', 'Hackney Wick, London E9', 'Hackney Wick', ARRAY['art','exhibition'], ARRAY['open studios','painting','sculpture'], '{}', true, NULL, NULL, 'https://www.hwickos.com', 'seed', 'seed-008'),
  ('Mycelium Network: A Living Archive', 'An immersive sound and light installation at ICA exploring the intelligence of forest networks.', '2026-05-05T11:00:00', '2026-06-18T18:00:00', 'ICA', 'The Mall, London SW1Y 5AH', 'Westminster', ARRAY['art','exhibition'], ARRAY['installation','sound art','mycology','ecology','generative'], '{}', false, 8.0, NULL, 'https://www.ica.art', 'seed', 'seed-009'),
  ('Zadie Smith in Conversation: The New Novel', 'Zadie Smith discusses her long-awaited new novel with journalist Nesrine Malik.', '2026-05-08T19:00:00', NULL, 'British Library', '96 Euston Rd, London NW1 2DB', 'Kings Cross', ARRAY['talk','literature'], ARRAY['fiction','writing','contemporary literature'], ARRAY['Zadie Smith','Nesrine Malik'], false, 12.0, NULL, 'https://www.bl.uk', 'seed', 'seed-010'),
  ('Yuval Noah Harari: AI and the Future of Human Consciousness', 'Yuval Noah Harari returns to London for a major talk on how AI is reshaping human cognition and democracy.', '2026-05-13T19:30:00', NULL, 'Royal Festival Hall', 'Belvedere Rd, London SE1 8XX', 'South Bank', ARRAY['talk'], ARRAY['AI','consciousness','history','future','philosophy'], ARRAY['Yuval Noah Harari'], false, 25.0, 40.0, 'https://www.southbankcentre.co.uk', 'seed', 'seed-011'),
  ('Robin Wall Kimmerer: Braiding Sweetgrass Live', 'Robin Wall Kimmerer, botanist and Potawatomi scholar, in conversation about plant intelligence and indigenous wisdom.', '2026-05-15T19:00:00', NULL, 'Southbank Centre', 'Belvedere Rd, London SE1 8XX', 'South Bank', ARRAY['talk'], ARRAY['ecology','botany','indigenous knowledge','nature','philosophy'], ARRAY['Robin Wall Kimmerer'], false, 20.0, NULL, 'https://www.southbankcentre.co.uk', 'seed', 'seed-012'),
  ('Adam Curtis: New Documentary Preview + Q&A', 'ICA screens the first 45 minutes of Adam Curtis''s new documentary series, followed by a rare extended Q&A.', '2026-05-11T19:00:00', NULL, 'ICA Cinema', 'The Mall, London SW1Y 5AH', 'Westminster', ARRAY['film','talk'], ARRAY['documentary','politics','media','BBC','Q&A'], ARRAY['Adam Curtis'], false, 14.0, NULL, 'https://www.ica.art', 'seed', 'seed-013'),
  ('Kate Crawford: AI Atlas — Power and Planetary Cost', 'AI researcher Kate Crawford presents new findings on the environmental and political costs of AI infrastructure.', '2026-05-18T18:30:00', NULL, 'LSE Old Theatre', 'Houghton St, London WC2A 2AE', 'Strand', ARRAY['talk','tech'], ARRAY['AI','climate','tech ethics','data centres'], ARRAY['Kate Crawford'], true, NULL, NULL, 'https://www.lse.ac.uk/Events', 'seed', 'seed-014'),
  ('Intelligence Squared: Does Consciousness Exist Outside the Brain?', 'Leading neuroscientists and philosophers debate with Anil Seth, Philip Goff, and Annaka Harris.', '2026-05-14T19:00:00', NULL, 'Emmanuel Centre', '9-23 Marsham St, London SW1P 3DW', 'Westminster', ARRAY['talk'], ARRAY['consciousness','neuroscience','philosophy','debate'], ARRAY['Anil Seth','Philip Goff','Annaka Harris'], false, 22.0, NULL, 'https://www.intelligencesquared.com', 'seed', 'seed-015'),
  ('Tarkovsky Season: Stalker (1979) — 4K Restoration', 'BFI screens the landmark 4K restoration of Andrei Tarkovsky''s Stalker.', '2026-05-06T20:00:00', NULL, 'BFI Southbank', 'Belvedere Rd, London SE1 8XT', 'South Bank', ARRAY['film'], ARRAY['Tarkovsky','Soviet cinema','sci-fi','restoration'], ARRAY['Andrei Tarkovsky','Robert Macfarlane'], false, 12.5, 16.5, 'https://www.bfi.org.uk', 'seed', 'seed-016'),
  ('Agnès Varda: Cléo from 5 to 7 — Restored Print', 'BFI screens the newly restored print of Agnès Varda''s masterpiece of the French New Wave.', '2026-05-08T18:30:00', NULL, 'BFI Southbank', 'Belvedere Rd, London SE1 8XT', 'South Bank', ARRAY['film'], ARRAY['French New Wave','Varda','classic cinema','feminism'], ARRAY['Agnès Varda'], false, 12.5, NULL, 'https://www.bfi.org.uk', 'seed', 'seed-017'),
  ('Werner Herzog in Conversation', 'An evening with Werner Herzog at Curzon Mayfair — the legendary filmmaker discusses his career and creative process.', '2026-05-19T19:00:00', NULL, 'Curzon Mayfair', '38 Curzon St, London W1J 7TY', 'Mayfair', ARRAY['film','talk'], ARRAY['documentary','cinema','Herzog','conversation'], ARRAY['Werner Herzog'], false, 28.0, NULL, 'https://www.curzon.com', 'seed', 'seed-018'),
  ('London AI Safety Research Meetup', 'Monthly gathering of AI safety researchers. This month: interpretability in large language models.', '2026-05-07T18:30:00', NULL, 'Google DeepMind London', '6 Pancras Square, London N1C 4AG', 'Kings Cross', ARRAY['tech','talk'], ARRAY['AI safety','alignment','interpretability','machine learning'], '{}', true, NULL, NULL, 'https://lu.ma/london-ai-safety', 'seed', 'seed-019'),
  ('AI & Creativity: Can Machines Be Artists?', 'Somerset House hosts a panel discussion with AI artists, researchers, and critics on generative AI and creativity.', '2026-05-10T18:00:00', NULL, 'Somerset House', 'Strand, London WC2R 1LA', 'Strand', ARRAY['tech','talk','art'], ARRAY['AI','creativity','generative art','ethics'], '{}', false, 15.0, NULL, 'https://www.somersethouse.org.uk', 'seed', 'seed-020'),
  ('React London: Advanced Patterns & Server Components', 'Monthly React London meetup — deep dive into React Server Components and Server Actions.', '2026-05-09T18:00:00', NULL, 'Skills Matter', '10 South Place, London EC2M 2RB', 'Moorgate', ARRAY['tech'], ARRAY['React','JavaScript','frontend','web development'], '{}', true, NULL, NULL, 'https://lu.ma/react-london', 'seed', 'seed-021'),
  ('Ted Chiang: Stories of Your Life — Discussion Evening', 'An intimate evening with Ted Chiang, author of Stories of Your Life (basis for the film Arrival). He reads from a new story.', '2026-05-12T19:00:00', NULL, 'Foyles Bookshop', '107 Charing Cross Rd, London WC2H 0DT', 'Soho', ARRAY['literature','talk'], ARRAY['science fiction','short stories','AI','language'], ARRAY['Ted Chiang'], false, 10.0, NULL, 'https://www.foyles.co.uk/events', 'seed', 'seed-022'),
  ('N.K. Jemisin: The World We Make — Book Launch', 'Hugo Award-winning author N.K. Jemisin launches her new novel at Waterstones Piccadilly.', '2026-05-14T18:30:00', NULL, 'Waterstones Piccadilly', '203-206 Piccadilly, London W1J 9HD', 'Piccadilly', ARRAY['literature','talk'], ARRAY['science fiction','Afrofuturism','book launch'], ARRAY['N.K. Jemisin'], false, 8.0, NULL, 'https://www.waterstones.com/events', 'seed', 'seed-023'),
  ('Ocean Vuong: Poetry Reading', 'LRB Bookshop hosts an intimate poetry reading with Ocean Vuong, followed by Q&A and book signing.', '2026-05-17T19:00:00', NULL, 'LRB Bookshop', '14 Bury Place, London WC1A 2JL', 'Bloomsbury', ARRAY['literature'], ARRAY['poetry','reading','LGBTQ+','American literature'], ARRAY['Ocean Vuong'], false, 12.0, NULL, 'https://lrbshop.co.uk/events', 'seed', 'seed-024'),
  ('Olga Tokarczuk: New Novel Discussion', 'Nobel Prize winner Olga Tokarczuk discusses her gothic novel with translator Antonia Lloyd-Jones.', '2026-05-20T19:00:00', NULL, 'The Barbican Library', 'Silk St, London EC2Y 8DS', 'City', ARRAY['literature','talk'], ARRAY['Polish literature','gothic','Nobel Prize','translation','mythology'], ARRAY['Olga Tokarczuk','Antonia Lloyd-Jones'], false, 10.0, NULL, 'https://www.barbican.org.uk', 'seed', 'seed-025'),
  ('Tanztheater Wuppertal Pina Bausch: Café Müller', 'The legendary Tanztheater Wuppertal brings Pina Bausch''s haunting masterpiece to Sadler''s Wells.', '2026-05-11T19:30:00', NULL, 'Sadler''s Wells', 'Rosebery Ave, London EC1R 4TN', 'Islington', ARRAY['theatre'], ARRAY['dance','contemporary dance','Pina Bausch'], ARRAY['Pina Bausch'], false, 25.0, 65.0, 'https://www.sadlerswells.com', 'seed', 'seed-026'),
  ('New Writing Night: Voices from the Margins', 'Bush Theatre''s monthly new writing showcase — five short plays by emerging playwrights.', '2026-05-08T19:30:00', NULL, 'Bush Theatre', '7 Uxbridge Rd, London W12 8LJ', 'Shepherd''s Bush', ARRAY['theatre'], ARRAY['new writing','emerging playwrights','short plays'], '{}', false, 8.0, NULL, 'https://www.bushtheatre.co.uk', 'seed', 'seed-027'),
  ('Nish Kumar: My Favourite Shapes — Live', 'Nish Kumar brings his acclaimed stand-up show to Leicester Square Theatre.', '2026-05-13T20:00:00', NULL, 'Leicester Square Theatre', '6 Leicester Place, London WC2H 7BX', 'West End', ARRAY['comedy'], ARRAY['stand-up','political comedy','live comedy'], ARRAY['Nish Kumar'], false, 20.0, NULL, 'https://www.leicestersquaretheatre.com', 'seed', 'seed-028'),
  ('Jon Hopkins Live Score to Koyaanisqatsi', 'Jon Hopkins performs a live electronic score to Godfrey Reggio''s landmark 1982 film Koyaanisqatsi.', '2026-05-22T19:30:00', NULL, 'Royal Festival Hall', 'Belvedere Rd, London SE1 8XX', 'South Bank', ARRAY['music','film'], ARRAY['electronic','live score','film','ambient'], ARRAY['Jon Hopkins'], false, 30.0, 55.0, 'https://www.southbankcentre.co.uk', 'seed', 'seed-029'),
  ('Ursula K. Le Guin Reading Circle: The Dispossessed', 'Monthly Le Guin reading circle discussing The Dispossessed — her anarchist utopia. Free, just turn up.', '2026-05-10T18:30:00', NULL, 'Housmans Bookshop', '5 Caledonian Rd, London N1 9DX', 'Kings Cross', ARRAY['literature'], ARRAY['science fiction','Le Guin','anarchism','book club'], '{}', true, NULL, NULL, 'https://www.housmans.com', 'seed', 'seed-030'),
  ('Robert Macfarlane: Landmarks — Walking, Writing, Wilderness', 'Robert Macfarlane in conversation about landscape, language, and the words we use to describe the natural world.', '2026-05-24T19:00:00', NULL, 'Royal Geographical Society', '1 Kensington Gore, London SW7 2AR', 'Kensington', ARRAY['talk','literature'], ARRAY['nature writing','landscape','wilderness','ecology','walking'], ARRAY['Robert Macfarlane'], false, 15.0, NULL, 'https://www.rgs.org', 'seed', 'seed-031')
ON CONFLICT (source, source_id) DO NOTHING;